# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:10.7-alpine

    steps:
      - checkout
      # - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev libpq-dev libgd-dev libxml2 libbz2-dev libzip-dev libonig-dev
      # - run: sudo docker-php-ext-install zip mysqli pdo pdo_pgsql bz2 bcmath pcntl intl gd mbstring
      # - run: sudo pecl install redis
      # - run: sudo docker-php-ext-enable redis
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.lock" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v4-{{ checksum "package.json" }}
            - node-v4-
      - run: npm install
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn

      - run: php vendor/phpunit/phpunit/phpunit
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output
